### ISSUE TITLE
Mendeley citation plugin fails to insert bibliography in LibreOffice

### ISSUE THREAD

**Issue by amaurypm** [flathub/com.elsevier.MendeleyDesktop#22] opened 2019-03-01 16:33 UTC
With the Mendeley Desktop installed from flathub I am unable to insert a bibliography in LibreOffice. I can insert citations, merge citations and everything else, but when trying to insert a bibliography the citation plugin fails without an error message and nothing happens. I am using Fedora 29 and the LibreOffice from Fedora's repos. The same happens when I use the LibreOffice from Flathub, and the same happens in Ubuntu 18.10, using the .deb from Mendeley site and LibreOffice from snap (not with the LibreOffice from Ubuntu's repo). I had to install MendeleyDesktop manually in Fedora, using the generic Linux package,  and now it works. I suppose it has something to do with the lack of permissions of sandboxed applications.

**Comment by Erick555** [comment] 2019-03-01 18:03
To clarify: after clicking on bibliography button in LO it pastes "Bibliography"header  in document for a short period which is then cleared - is this the same what you see?

**Comment by amaurypm** [comment] 2019-03-01 18:48
@Erick555 : The same.

**Comment by Erick555** [comment] 2019-03-01 21:49
The LO plugin is communicating through local network. I don't know what we can do here. @cho2 did you spot the same issue?

**Comment by cho2** [comment] 2019-03-02 06:22
@Erick555 yes, I got the same issue, someone on Endless Community face this problem too (https://community.endlessos.com/t/mendeley-on-endless-cant-login/5670/10). I already reported an issue on the plugin page (https://github.com/Mendeley/openoffice-plugin/issues/48). 

I don't know it's the problem on LibreOffice or the latest Mendeley plugin, because when I try on LibreOffice+Mendeley on OS X, it's work well.

**Comment by Erick555** [comment] 2019-03-02 11:02
Ok, thx for the info. Version 1.19.4 of Mendeley will be released soon, maybe it will fix this.

**Comment by nise** [comment] 2019-03-15 12:59
I can confirm this problem. The plugin installs without problems and its controls appear in LibreOffice, but they are not responding.

Since Mendeley for Linux is only available at version 1.19.3 I have no chance to compile the lattest source provided here at GitHub.

I started libre office from the command line but did not get any output regarding the plug,

Is there a way other to debug the plugin?

Please remember the importance of this issue. In case the plugin is not functional Mendeley becomes useless for the Linux users.

**Comment by nise** [comment] 2019-03-15 13:00
@Erick555 could you be please more precise. What is the planed release date?

**Comment by Erick555** [comment] 2019-03-15 15:25
> Since Mendeley for Linux is only available at version 1.19.3 I have no chance to compile the lattest source provided here at GitHub.

What do you mean? We use the 1.19.3 version here in GitHub (also there is nothing to compile, it just downloads binaries released by Mendeley).

> Is there a way other to debug the plugin?

I couldn't figure it out, same as you.

> Please remember the importance of this issue. In case the plugin is not functional Mendeley becomes useless for the Linux users.

I did everything I could to maintain flatpak package in best possible way but I can't affect how Mendeley app itself works. Flatpak package is a pure community effort.

> could you be please more precise. What is the planed release date?

I don't know. Only development pre-releases are [available](https://www.mendeley.com/autoupdates/installers/preview) for now. I could be a couple of weeks. Keep in mind that there is no guarantee that new releases will fix anything.

**Comment by cho2** [comment] 2019-04-10 04:47
still not work in 1.19.4

**Comment by Erick555** [comment] 2019-04-10 10:55
I know. As you can see there was [no activity regarding plugin for couple of months](https://github.com/Mendeley/openoffice-plugin).

**Comment by bmreilly** [comment] 2019-07-27 22:30
Has this issue made any progress? I'm experiencing the same issue right now. insert bibiliography only prints the header "{Bibliography}" and nothing else happens. Initially it printed then disappeared leaving nothing in its place, but after going through my mendeley library and manually clicking the check mark for "are these details correct?"  it seems like "{Bibliography}" is staying in place.

**Comment by Erick555** [comment] 2019-07-28 11:46
Unfortunately no.

**Comment by Erick555** [comment] 2019-08-02 22:08
@amaurypm @cho2 @nise @bmreilly 

I believe I made a breakthrough in https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/24 . [Please test](https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/24#issuecomment-517857885) and confirm if it work for you. Keep in mind that Libreoffice have to have access to /tmp from host (you may need to pass `flatpak override --filesystem=/tmp org.libreoffice.LibreOffice`)

**Comment by cho2** [comment] 2019-08-03 15:05
@Erick555 
[Tested](https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/24) and it works on me (Flatpak 1.2.3 on openSUSE Leap 15.1), but `flatpak override --filesystem=/tmp org.libreoffice.LibreOffice` need run as root.

**Comment by Erick555** [comment] 2019-08-03 15:46
Thx for confirming, I'll merge it soon. `flatpak override` needs root if you install flatpaks to `/var/lib/flatpak`, AKA system-wide.

**Closed as completed** 2019-08-04 10:49 UTC

**Comment by kelumkel** [comment] 2019-10-19 20:22
I had the same problem.  
I followed following and worked. 
https://blog.kukuh.syafaat.id/2018/LibreOffice-and-Mendeley-Desktop-Flatpak/
Better to uninstall current version of LO and Medeley before following above (but for me uninstallation of the two packages was not required).

**Comment by Erick555** [comment] 2019-10-20 11:08
@kelumkel same instructions are provided in [readme](https://github.com/flathub/com.elsevier.MendeleyDesktop#known-issues). There is no need to uninstall LO or Mendeley.

**Comment by waboke** [comment] 2022-08-16 23:06
i install mendeley succcesfully with libreoffice with plugin. my problem is that when i click the insert citation button the mendeley desktop will open like that without the waiting for the citation editor

**Comment by yayosry** [comment] 2023-03-28 06:11
> @Erick555 [Tested](https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/24) and it works on me (Flatpak 1.2.3 on openSUSE Leap 15.1), but `flatpak override --filesystem=/tmp org.libreoffice.LibreOffice` need run as root.

mendeley 1.19.8  and libreoffice 7.5.1.2 flatpak, on linux mint 21.1

i use this and works.    thank you

**Comment by paulbrodersen** [comment] 2023-06-19 14:47
I had the same issue as OP on Ubuntu 18.04 LTS with libreoffice 6.0.7.3 and mendeley plugin 1.19.8. In my case, the problem was somehow caused by an interaction with "Track changes". The solution was to "Accept all changes" and turn off "Track changes".

**Comment by cement-head** [comment] 2024-02-22 14:42
Still broken for me.
